$color = rgba(1, 1, 1, 1)
$inner_color = rgba(1, 1, 1, 0.66)
$outer_color = rgba(255, 102, 255, 1)
$font_color = rgba(238, 238, 232, 1)
$placeholder_color = rgba(238, 238, 232, 0.7)
$check_color = rgba(164, 185, 210, 1)
